# Utilizează o imagine de bază cu serverul web
FROM nginx:latest

# Copiază fișierul HTML în directorul de bază al serverului
COPY /var/lib/jenkins/workspace/Jenkins-docker/repo/Docker/index.html /usr/share/nginx/html/
